softeerbootcamp-3rd/Team1-driving-today

.gitignore
backend/driving-today/src/main/java/com/drivingtoday/config/SwaggerConfig.java
backend/driving-today/src/main/java/com/drivingtoday/controller/TestController.java
backend/driving-today/src/main/java/com/drivingtoday/entity/Academy.java
backend/driving-today/src/main/java/com/drivingtoday/entity/Instructor.java
backend/driving-today/src/main/java/com/drivingtoday/entity/Reservation.java
backend/driving-today/src/main/java/com/drivingtoday/entity/Review.java
backend/driving-today/src/main/java/com/drivingtoday/entity/Student.java

- close #2 
- Reservation, Student, Instructor, Academy, Review 엔티티 작성 완료
- JPA cascade, updatable, 양방향 매핑 차후 필요시 도입 예정

feat: 엔티티 생성

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/main.tsx
frontend/src/styles/theme.ts

- close #17 
- emotion 설치
- theme 설정

[FE] theme provider setup

---

backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java

- dev브랜치로 merge 과정에서 빌드가 안되는 문제 발생 -> Reservation entity에서 student 필드 중복된 것을 확인하고 해결 
- feat/reservation->dev merge 과정에서 conflict 발생했었는데, 그 과정에서 필드가 중복으로 작성되는 문제가 발생한 것 같음

[BE] bugfix : student 필드 중복문제 해결

---

.github/workflows/deploy_main.yml
.github/workflows/deploy_test.yml

[BE] ci : scp-action 버전 수정

---

frontend/src/components/chip/README.md
frontend/src/components/chip/chip.tsx
frontend/src/components/chip/index.ts

[FE] feat: chip component

---

frontend/.eslintrc.cjs
frontend/package.json
frontend/pnpm-lock.yaml
frontend/tsconfig.json
frontend/vite.config.ts

- close #30 
- thanks to @junhea [vite & ts & eslint 에서 import alias 설정하기](https://github.com/softeerbootcamp-3rd/Team1-driving-today/wiki/vite-&-ts-&-eslint-%EC%97%90%EC%84%9C-import-alias-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)

[FE] feat: path alias with vite

---

frontend/vite.config.ts

bugfix: failed to resolve path

---

backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewFindService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewRepository.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewFindRequest.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewInfo.java
backend/driving-today/src/main/resources/data.sql
backend/driving-today/src/test/java/com/drivingtoday/domain/review/ReviewFindServiceTest.java

- close #62 
- 기존 강사 상세 정보 조회 API로부터 리뷰 조회에 관한 기능 및 테스트 코드 전부 분리
- 페이징 기능 구현, 최신 리뷰 순으로 정렬해서 반환
- 파라미터 검증 + 예외 처리

[BE] feat : 특정 강사에 대한 리뷰 조회 API 개발

---

backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentFindService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/student/dto/StudentInfo.java
backend/driving-today/src/test/java/com/drivingtoday/domain/student/StudentFindServiceTest.java

- close #79 
- 강사 페이지에서 학생을 클릭했을 때 학생 정보를 조회하는 API 개발

[BE] feat : 학생 정보 조회 API 개발

---

frontend/src/App.tsx
frontend/src/pages/dashboard/page.tsx
frontend/src/pages/history/page.tsx
frontend/src/pages/layout.tsx
frontend/src/pages/login/page.tsx
frontend/src/pages/page.tsx
frontend/src/pages/purchase/page.tsx
frontend/src/pages/schedule/page.tsx

- close #71
- 폴더구조 잡기
- `layout.tsx` 에서 페이지 레이아웃 관리
- 같은 route에서 강사/학생을 처리하고 있기 때문에 분기 처리하여 렌더링함
```jsx
<Route
path="/dashboard"
element={
<RequireAuth>
{({ isStudent }) => {
return isStudent ? <StudentDashboard /> : <InstructorDashboard />
}}
</RequireAuth>
}
/>
```

[FE] feat: 폴더구조 작성

---

frontend/src/components/card/README.md
frontend/src/components/card/card.tsx
frontend/src/components/card/index.ts

- close #87
- 최대한 재사용하면서 다양한 상황에 맞게 컴포넌트 만들기
- 각 버튼의 콜백 함수를 선택으로 받아, undefined일 경우 버튼을 숨기도록 설계하였습니다

[FE] feat: card component

---

frontend/src/hooks/use-fetch.ts

[FE] feat: useFetch hook

---

frontend/index.html
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/App.tsx
frontend/src/components/icon/icon.tsx
frontend/src/pages/layout.tsx
frontend/src/pages/schedule/page.tsx
frontend/tsconfig.json

- close #94 
- 연수 예약 폼 작성
- 카카오 지도 연동
- 현재 위치 받아오기

[FE] feat: search instructor form

---

backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationInstructorResponse.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationStudentResponse.java

- close #102 
- 예약 정보 응답에 강사, 학생 id 추가

[BE] feat : 예약 정보 응답에 강사, 학생 id 추가

---

frontend/src/hooks/use-fetch.ts

[FE] hotfix: useFetch fix dependency

---

backend/driving-today/src/main/java/com/drivingtoday/global/config/CorsConfig.java

- close #97 
- cors config 파일 추가(임시로 전체 허용)

[BE] cors config

---

backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorFindService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorRepository.java
backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/AvailableInstructorInfo.java
backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/dto/InstructorDetailResponse.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewRepository.java
backend/driving-today/src/main/resources/data.sql

- close #105 
- 강사 리스트, 강사 상세 정보 조회 페이지에서 강사 평점까지 반환하도록 구현

[BE] feat : 강사 평점 조회 기능 추가

---

backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationAddService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationRepository.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/exception/ReservationErrorCode.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/exception/ReservationException.java

- close #116
- 예약 동시간대에 접수 못하게 막는 로직
- 각 domain마다 exception 폴더 만들어서 error code와 exception 파일 만들고 exception manager 만듬
- exception manager는 이미 다른 팀원이 만들어둬서 conflict 나니까 만들어놓고 testing해보고 지움

[BE] feat : 예약 동시간대에 접수 못하게 막는 로직 구현

---

backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewAddService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/exception/ReviewErrorCode.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/exception/ReviewException.java
backend/driving-today/src/main/java/com/drivingtoday/global/exception/ExceptionManager.java

- close #119
- 리뷰 컨트롤러에 Authentication 로직 추가
- 리뷰 서비스 student 설정 로직 변경

feat : 리뷰 컨트롤러, 서비스에 로그인 로직 추가

---

frontend/src/assets/icons/close.svg
frontend/src/assets/icons/index.ts
frontend/src/components/card/card.tsx
frontend/src/components/tab/tab.tsx
frontend/src/hooks/use-fetch.ts
frontend/src/pages/history/components/cardlist/cardlist.tsx
frontend/src/pages/history/components/cardlist/index.ts
frontend/src/pages/history/components/modal/index.ts
frontend/src/pages/history/components/modal/modal.tsx
frontend/src/pages/history/page.tsx
frontend/src/utils/constants.ts

- close #74 
- close #76 
- 재사용성을 늘리기 위해 코드를 리팩터링하다보니 오버 엔지니어링의 늪에 빠지게 되었다 (구해줘서 고마워 정진아!)
- setState 내부에서 다른 state를 조작하면 안된다

[FE] feat: history page

---

backend/driving-today/src/main/java/com/drivingtoday/global/config/SwaggerConfig.java

- close #99 
- swagger 상 로그인 기능 설정
-

[BE] feat : Swagger 로그인 설정

---

frontend/src/components/header/header.tsx
frontend/src/components/sidebar/sidebar.tsx

[FE] feat: update layout

---

backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewDetail.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewInfo.java

- close #130 
- 리뷰 응답에 리뷰 작성자 사진 정보 추가

[BE] feat : 리뷰 응답에 리뷰 작성자 사진 정보 추가

---

backend/driving-today/src/main/java/com/drivingtoday/global/config/CorsConfig.java

- CorsConfig 파일에 allowedHeaders("Authorization") 추가

[BE] chore : cors allowHeaders 추가

---

frontend/src/pages/purchase/page.tsx
frontend/src/pages/search/page.tsx

feat: purchase page markup

---

backend/driving-today/build.gradle
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/WebSocketHandler.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatMessage.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatRoom.java
backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java
backend/driving-today/src/main/java/com/drivingtoday/global/config/WebSocketConfig.java
backend/driving-today/src/main/java/com/drivingtoday/global/config/WebSocketHandShakeInterceptor.java
backend/driving-today/src/main/java/com/drivingtoday/global/user/UserJoinController.java

- close #148
- jwt chat 구현 (mongo db x)
- interceptor 추가

[BE] feat : signup 포스트맨 안되던거 해결 완료, chat with jwt

---

backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatRoomRepository.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/WebSocketHandler.java

- close #164
- 강사가 본인에게 온 메시지들 톡방 리스트
- Paging 하기는 이전, 반환 타입 리팩토링 추후 필요
- 프론트 측과 논의 필요. 작동 확인 후 바로 컨트롤러 및 서비스계층 리팩토링 필요.

[BE] feat :  chat api 강사가 본인에게 온 메시지들 톡방 리스트화 API

---

frontend/package.json
frontend/pnpm-lock.yaml

feat: setting vitest

---

backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentController.java

- close #178 
- 연수생이 쓰는 api에는 /student를, 강사가 쓰는 api에는 /instructor 추가

feat: 연수생용, 강사용 api에 각각 /student, /instructor 추가

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/App.tsx
frontend/src/components/flex/flex.tsx
frontend/src/components/flex/index.ts
frontend/src/components/typography/index.ts
frontend/src/components/typography/typography.tsx
frontend/src/pages/purchase/loader.ts
frontend/src/pages/purchase/page.tsx
frontend/src/pages/purchase/success/page.tsx

- close #163 
자주 사용되는 컴포넌트라 `components` 폴더로 분리하였습니다.
https://github.com/softeerbootcamp-3rd/Team1-driving-today/assets/33178048/1da6b6bd-5397-42c9-a016-4fa9e638864c

[FE] feat: 연수 예약 API 연동 

---

backend/driving-today/build.gradle
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatMessageRepository.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatMessageService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/WebSocketHandler.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatMessage.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatRoomInfo.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatRoomInfoConcise.java
backend/driving-today/src/main/java/com/drivingtoday/domain/chat/model/ChatRoomInfoDetail.java
backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java

- close #185 
- mongo database 추가에 따른 ChatMessage 저장 및 관리
- ChatRoom DTO 작성
- Chat Domain Controller 어떤 role이 url 접근하냐에 따라 분리
- mongo repository
- mongo service 작성
- dependency added

[BE] feat : mongodb chat

---

backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorFindService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentController.java

- close #192 
- /student/my api
- /instructor/my api

feat : 로그인한 연수생, 강사 정보 반환 API

---

frontend/src/App.tsx
frontend/src/hooks/use-chat-socket.ts
frontend/src/main.tsx
frontend/src/pages/components/chat-modal/chat-modal.tsx
frontend/src/providers/chat-modal-provider.tsx
frontend/src/utils/session.ts

- close #197
- socket 관리 방법
- modal 표시 방법
- modal 관리 방법

[FE] feat: chat modal and hook

---

backend/driving-today/build.gradle
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationLockFacade.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationRepository.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationRequest.java
backend/driving-today/src/test/java/com/drivingtoday/domain/instructor/InstructorFindServiceTest.java
backend/driving-today/src/test/java/com/drivingtoday/domain/reservation/ReservationConcurrencyTest.java
backend/driving-today/src/test/java/com/drivingtoday/domain/review/ReviewAddServiceTest.java

- close #152 
- Redisson의 분산락을 이용한 동시성 문제 해결
- 동시성 테스트 코드 작성

[BE] feat : Redisson을 이용한 동시성 문제 해결

---

backend/driving-today/src/main/java/com/drivingtoday/domain/academy/Academy.java
backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorFindService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/exception/InstructorErrorCode.java
backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/exception/InstructorException.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationAddService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationLockFacade.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/exception/ReservationErrorCode.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewAddService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/exception/ReviewErrorCode.java
backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentFindService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/student/exception/StudentErrorCode.java
backend/driving-today/src/main/java/com/drivingtoday/domain/student/exception/StudentException.java
backend/driving-today/src/main/java/com/drivingtoday/global/exception/ExceptionManager.java

- close #208 
- 해당 도메인에 맞는 에러 분류 및 에러 처리 부분 수정

[BE] feat : 도메인별 에러 처리

---

backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java

[BE] bugfix :  JwtFilter alloList 수정

---

backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java
backend/driving-today/src/main/java/com/drivingtoday/global/config/HealthCheckController.java

[BE] feat : 로드밸런서의 상태 확인용 api

---

frontend/src/utils/session.ts

[FE] feat: save session to browser

---

backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java

- close #235 
- Reivew 엔티티에 Reservation 매핑 추가

[BE] feat : Review 엔티티 연관 관계 추가

---

backend/driving-today/src/main/java/com/drivingtoday/global/.gitkeep

[BE] hotfix : 테이블 구조 변경을 위한 커밋

---

backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
backend/driving-today/src/main/java/com/drivingtoday/global/.gitkeep

- boolean 타입을 bit -> tinyint로 변경

[BE] hotfix : 테이블 boolean 타입 변경

---

frontend/src/pages/dashboard/components/calendar/components.tsx
frontend/src/pages/schedule/page.tsx

- close #216 
- date picker 스타일 수정

[FE] feat: search page date picker component

---

backend/driving-today/src/main/java/com/drivingtoday/global/.gitkeep

[BE] hotfix : 인프라 작업에 따른 cicd 세팅

---

frontend/src/pages/history/components/cardlist/cardlist.tsx
frontend/src/pages/history/components/modal/modal.tsx
frontend/src/pages/history/page.tsx
frontend/src/types/reservation.ts

- close #184
- ~~거절 로직 구현 필요~~ 완료
- 학생 기록 리스트에서 정렬 필요
- #191 반영후 수정해야 함

[FE] feat: use api in history page

---

backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/Reservation.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationListService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/dto/ReservationStudentResponse.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/Review.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewAddService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewRequest.java

- close #233 
- 지난 예약 리스트 응답 dto에 리뷰가 작성되었는지 여부 포함
- Reservation에도 Review 1:1 매핑

[BE] feat : 지난 예약 리스트에 리뷰 작성 여부 포함

---

frontend/src/pages/components/chat-modal/chat-home/chat-home.tsx

[FE] fix: fix student info card in chat modal home

---

frontend/src/App.tsx
frontend/src/pages/components/landing/first-stage.tsx
frontend/src/pages/components/landing/landing.tsx
frontend/src/pages/components/landing/second-stage.tsx
frontend/src/pages/components/landing/third-stage.tsx
frontend/src/pages/page.tsx
frontend/src/providers/scroll-animation-provider.tsx

- close #249
- 랜딩 페이지 스타일 개선: 배경, 헤더 등
- 랜딩 페이지 렌더러 개선: css transition으로 ease하지 않고 자체적으로 ease 하도록
- 로그인 상태에 따라 각각 다른 헤더 표시
문구 추가 해야합니다

[FE] feat: enhance landing page

---

frontend/src/pages/components/auth-modal/components/academy-field.tsx
frontend/src/pages/components/auth-modal/components/index.ts
frontend/src/pages/components/auth-modal/components/text-field.tsx
frontend/src/pages/components/auth-modal/components/textarea-field.tsx
frontend/src/pages/components/auth-modal/register-modal.tsx
frontend/src/pages/components/auth-modal/styles.tsx

- close #215 
- #234
- 최대한 브라우저 기본 api 활용 및 인터페이스 유지

[FE] feat: register login validation

---

frontend/src/pages/history/components/cardlist/cardlist.tsx
frontend/src/pages/history/components/modal/modal.tsx
frontend/src/pages/history/page.tsx
frontend/src/types/reservation.ts

- close #248 
- 리뷰 모달에서 리뷰 완료시 형제 컴포넌트의 자식에서 리뷰 버튼을 숨겨야 하는데 이를 어떻게 전달할 것인지 -> forwardRef + imperativeHandle

[FE] feat: distinguish reviewed reservations from history

---

backend/driving-today/src/main/java/com/drivingtoday/global/user/UserRegisterService.java

- close #270 
- https://drivingtodaybucket.s3.ap-northeast-2.amazonaws.com/profile/default.jpg 이미지로 지정

[BE] feat : 회원가입시 사진 입력을 안하면 기본이미지로 세팅

---

backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewFindService.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewRepository.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/dto/ReviewInfo.java
backend/driving-today/src/main/java/com/drivingtoday/global/dto/SliceResponse.java

- close #275 
- fetch join을 적용한 N+1 문제 해결

[BE] refactor : 리뷰 리스트 조회 쿼리 성능 개선

---

frontend/src/components/card/card.tsx
frontend/src/components/lazy-image/index.ts
frontend/src/components/lazy-image/lazy-image.tsx
frontend/src/components/logo/logo.tsx
frontend/src/pages/components/auth-modal/register-modal.tsx
frontend/src/pages/components/chat-modal/chat-home/chat-home.tsx
frontend/src/pages/components/chat-modal/chat-room/styles.tsx
frontend/src/pages/components/landing/second-stage.tsx
frontend/src/pages/dashboard/components/myprofile-card/myprofile-card.tsx
frontend/src/pages/reservation/page.tsx
frontend/src/pages/reservation/search/components/detail-dialog/instructor-detail.tsx

- close #259 
- ux 개선을 위한 image lazy load

[FE] feat: lazy load image

---

backend/driving-today/src/main/java/com/drivingtoday/domain/chat/ChatController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/instructor/InstructorController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/reservation/ReservationController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/review/ReviewController.java
backend/driving-today/src/main/java/com/drivingtoday/domain/student/StudentController.java
backend/driving-today/src/main/java/com/drivingtoday/global/auth/config/JwtFilter.java
backend/driving-today/src/main/java/com/drivingtoday/global/auth/constants/Authentication.java
backend/driving-today/src/main/java/com/drivingtoday/global/auth/jwt/AuthenticationContextHolder.java
backend/driving-today/src/main/java/com/drivingtoday/global/config/WebSocketHandShakeInterceptor.java
backend/driving-today/src/main/java/com/drivingtoday/global/user/TestController.java
backend/driving-today/src/test/java/com/drivingtoday/global/user/UserLoginServiceTest.java

[BE] feat : AuthenticationContextHolder로 Authentication 전파

---

frontend/src/App.tsx
frontend/src/components/sidebar/sidebar.tsx
frontend/src/hooks/use-chat-socket.ts
frontend/src/hooks/use-fetch.ts
frontend/src/pages/components/auth-modal/components/academy-field.tsx
frontend/src/pages/components/chat-modal/chat-home/chat-home.tsx
frontend/src/pages/components/chat-modal/chat-room/chat-room.tsx
frontend/src/pages/components/landing/second-stage.tsx
frontend/src/pages/dashboard/components/schedule-card/schedule-card.tsx
frontend/src/pages/history/components/cardlist/cardlist.tsx
frontend/src/pages/layout.tsx
frontend/src/pages/login/page.tsx
frontend/src/pages/page.tsx
frontend/src/pages/reservation/search/components/detail-dialog/instructor-detail.tsx
frontend/src/pages/reservation/search/page.tsx
frontend/src/utils/api.ts
frontend/src/utils/constants.ts
frontend/src/utils/is-error-instance.ts
frontend/src/utils/session.ts

- close #281 
- `errerElement` 에 에러 메세지 보이도록 수정
- 로그아웃 기능
- 학원 검색 API 토큰 검사 안하도록 수정

[FE] fix: resolve token error
